name: Setup
description: Set up project environment and test environment.
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 18
        registry-url: https://registry.npmjs.org
        cache: yarn

    - uses: actions/cache@v3
      id: install-cache
      with:
        path: .yarn/
        key: ${{ runner.os }}-install-${{ hashFiles('**/install-state.gz') }}

    - if: steps.install-cache.outputs.cache-hit != 'true'
      run: |
        yarn set version berry
        yarn
      shell: bash
