compressionLevel: mixed
nodeLinker: node-modules
enableGlobalCache: false

yarnPath: .yarn/releases/yarn-4.1.0.cjs

packageExtensions:
  "@gnolang/tm2-js-client@*":
    dependencies:
      "@bufbuild/protobuf": "*"
