compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

packageExtensions:
  "@gnolang/tm2-js-client@*":
    dependencies:
      "@bufbuild/protobuf": "*"

yarnPath: .yarn/releases/yarn-4.17.1.cjs
