import { MAX_TICK, MIN_TICK } from "./swap.constant";

export const LIQUIDITY_GRAPH_BIN_COUNT = 40 as const;

const LIQUIDITY_GRAPH_FULL_TICK_RANGE = MAX_TICK - MIN_TICK;

export const LIQUIDITY_GRAPH_VISIBLE_TICK_RANGES = [
  LIQUIDITY_GRAPH_FULL_TICK_RANGE,
  386_000,
  84_000,
  18_240,
  3_960,
  880,
  200,
  LIQUIDITY_GRAPH_BIN_COUNT,
] as const;

export const LIQUIDITY_GRAPH_INITIAL_ZOOM_LEVEL = 3 as const;

export const LIQUIDITY_GRAPH_DEFAULT_VISIBLE_TICK_RANGE =
  LIQUIDITY_GRAPH_VISIBLE_TICK_RANGES[LIQUIDITY_GRAPH_INITIAL_ZOOM_LEVEL];

export const SWAP_TOKEN_CHART_COLORS = {
  GRADIENT: {
    START: "rgba(25, 46, 162, 0.5)",
    END: "rgba(25, 46, 162, 0.02)",
  },
};
